# General Experiment Settings
SEED: 30                              
NUM_SEEDS: 16                         
LOAD_PATH: /nas/ucb/sandytanwisuth/ser/value-of-intent/saved_models/20250225/cramped_room/ub_ippo_oc_cramped_room_20250225_173039_30

# Environment Settings
ENV_NAME: "overcooked"                
ENV_KWARGS: 
  layout: "cramped_room"             

ACTIVATION: "tanh"                    # tanh or relu

# PPO Hyperparameters
LR: 2.5e-4                           
ANNEAL_LR: true                       
NUM_ENVS: 16                          
NUM_STEPS: 128                        
TOTAL_TIMESTEPS: 5e7                  # 5e7 for lb and op, 4e8 for ub
UPDATE_EPOCHS: 4                     
NUM_MINIBATCHES: 4                    
GAMMA: 0.99                           
GAE_LAMBDA: 0.95                      
CLIP_EPS: 0.2                        
ENT_COEF: 0.01                        
VF_COEF: 0.5                          
MAX_GRAD_NORM: 0.5                    
REW_SHAPING_HORIZON: 2.5e7            

# WandB Integration
ENTITY: "sandily"                     
PROJECT: "comparisons"                
WANDB_MODE: "online"                  