# General Experiment Settings
SEED: 30                              
NUM_SEEDS: 64                        
LOAD_PATH: /nas/ucb/sandytanwisuth/ser/value-of-intent/saved_models/20250301/asymm_advantages/ub_asymm_advantages_20250301_104318_30/

# Architecture Settings
ARCHITECTURE: "cnn"                   # "cnn", "ff", "rnn"

# CNN-specific parameters
CNN_CONFIG:
  features: [32, 32, 32]             # Number of features per conv layer
  kernel_sizes: [[5, 5], [3, 3], [3, 3]]  # Kernel sizes per layer
  dense_features: 64                 # Features in final dense layer

# FF-specific parameters
FF_CONFIG:
  hidden_layers: [64, 64]            # Size of hidden layers

# RNN-specific parameters
RNN_CONFIG:
  hidden_sizes: [64, 64]  # Size of hidden layers in RNN
  dense_features: 64      # Size of final dense layer

USE_CPC: true

CPC_ENCODER: "cnn"  # could be "ff", "rnn"
CPC_CONFIG:
  projection_dim: 128
  gru_hidden_dim: 256
  num_future_steps: 8
  temperature: 0.1

  
# Environment Settings
ENV_NAME: "overcooked"                
ENV_KWARGS: 
  layout: "asymm_advantages"         

ACTIVATION: "relu"                    # tanh or relu

# PPO Hyperparameters
LR: 1e-3                         # 1e-3, 0.000025 for ff
ANNEAL_LR: true                       
NUM_ENVS: 64                          # 128 for ub, 16 for lb and op
NUM_STEPS: 256                        
TOTAL_TIMESTEPS: 5e7                  # 5e7 for lb and op, 4e8 for ub
UPDATE_EPOCHS: 4                      
NUM_MINIBATCHES: 16                    # 16 for cnn, 4 for ff
GAMMA: 0.98                           
GAE_LAMBDA: 0.95                      
CLIP_EPS: 0.1                         
ENT_COEF: 0.02                        
VF_COEF: 0.5                          
MAX_GRAD_NORM: 0.5                    
REW_SHAPING_HORIZON: 2.5e6            # ~10% of total timesteps

# Transformer Settings
SEQ_LEN: 5

# WandB Integration
ENTITY: "sandily"                     
PROJECT: "comparisons"                
WANDB_MODE: "online"                 