# General Experiment Settings
SEED: 30                             
NUM_SEEDS: 128                       
LOAD_PATH: /nas/ucb/sandytanwisuth/ser/value-of-intent/saved_models/20250228/coord_ring/ub_coord_ring_20250228_165554_30

# Environment Settings
ENV_NAME: "overcooked"                
ENV_KWARGS: 
  layout: "coord_ring"                

ACTIVATION: "tanh"                    

# PPO Hyperparameters
LR: 0.00005                           
ANNEAL_LR: true                       
NUM_ENVS: 128                         # 128 for ub, 16 for lb and op: change to 32, 64 or 128 for lb and op
NUM_STEPS: 128                        
TOTAL_TIMESTEPS: 4e8                  # 4e8 for all
UPDATE_EPOCHS: 4                      
NUM_MINIBATCHES: 4                    
GAMMA: 0.99                           # 0.99 or 0.98 seem to both work okay
GAE_LAMBDA: 0.95                      
CLIP_EPS: 0.2                         
ENT_COEF: 0.05                        # 0.05 intuition might get better because preventing getting stuck in local_min
VF_COEF: 0.5                          
MAX_GRAD_NORM: 0.5                    
REW_SHAPING_HORIZON: 2.5e7      

# Transformer Settings
SEQ_LEN: 5

# WandB Integration
ENTITY: "sandily"                    
PROJECT: "comparisons"                
WANDB_MODE: "online"                  