# General Experiment Settings
SEED: 30                              
NUM_SEEDS: 10                         
LOAD_PATH: /nas/ucb/sandytanwisuth/ser/value-of-intent/saved_models/20250301/counter_circuit/ub_counter_circuit_20250301_104620_30

# Architecture Settings
ARCHITECTURE: "cnn"                   # "cnn", "ff", "rnn"

# CNN-specific parameters
CNN_CONFIG:
  features: [32, 32, 32]             # Number of features per conv layer
  kernel_sizes: [[5, 5], [3, 3], [3, 3]]  # Kernel sizes per layer
  dense_features: 64                 # Features in final dense layer

# FF-specific parameters
FF_CONFIG:
  hidden_layers: [64, 64]            # Size of hidden layers

# RNN-specific parameters
RNN_CONFIG:
  hidden_sizes: [64, 64]  # Size of hidden layers in RNN
  dense_features: 64      # Size of final dense layer

# Environment Settings
ENV_NAME: "overcooked"                
ENV_KWARGS: 
  layout: "counter_circuit"         

ACTIVATION: "relu"                    # tanh or relu, use relu in CNN

# PPO Hyperparameters
LR: 0.0005                          
ANNEAL_LR: true                       
NUM_ENVS: 64                         # 128 generally, try 64 for now
NUM_STEPS: 256                        
TOTAL_TIMESTEPS: 4e8                  # 5e7 for lb and op, 4e8 for ub
UPDATE_EPOCHS: 4                      
NUM_MINIBATCHES: 16                   # increased from 4 in FF to 16 in CNN
GAMMA: 0.99                           
GAE_LAMBDA: 0.95                      
CLIP_EPS: 0.2                         
ENT_COEF: 0.01                        
VF_COEF: 0.5                          
MAX_GRAD_NORM: 0.5                    
REW_SHAPING_HORIZON: 2.5e7   

# WandB Integration
ENTITY: "sandily"                     
PROJECT: "comparisons"                
WANDB_MODE: "online"                 