# General Experiment Settings
SEED: 30                              
NUM_SEEDS: 128                         
LOAD_PATH: /nas/ucb/sandytanwisuth/ser/value-of-intent/saved_models/20250228/counter_circuit/ub_ippo_oc_counter_circuit_20250228_121323_30/

# Environment Settings
ENV_NAME: "overcooked"                
ENV_KWARGS: 
  layout: "counter_circuit"         

ACTIVATION: "tanh"                    # tanh or relu

# PPO Hyperparameters
LR: 0.0001                          
ANNEAL_LR: true                       
NUM_ENVS: 128                         # 128 for ub
NUM_STEPS: 128                        
TOTAL_TIMESTEPS: 4e8                  # 5e7 for lb and op, 4e8 for ub
UPDATE_EPOCHS: 4                      
NUM_MINIBATCHES: 4                    
GAMMA: 0.98                           
GAE_LAMBDA: 0.95                      
CLIP_EPS: 0.2                         
ENT_COEF: 0.05                        
VF_COEF: 0.5                          
MAX_GRAD_NORM: 0.5                    
REW_SHAPING_HORIZON: 2.5e7            

# WandB Integration
ENTITY: "sandily"                     
PROJECT: "comparisons"                
WANDB_MODE: "online"                 