# General Experiment Settings
SEED: 30                              
NUM_SEEDS: 64                      
LOAD_PATH: /nas/ucb/sandytanwisuth/ser/value-of-intent/saved_models/20250314/cramped_room/ub_cnn_cramped_room_20250314_133108_30

# Architecture Settings
ARCHITECTURE: "rnn"                   # "cnn", "ff", "rnn"

# CNN-specific parameters
CNN_CONFIG:
  features: [32, 32, 32]             # Number of features per conv layer
  kernel_sizes: [[5, 5], [3, 3], [3, 3]]  # Kernel sizes per layer
  dense_features: 64                 # Features in final dense layer

# FF-specific parameters
FF_CONFIG:
  hidden_layers: [64, 64]            # Size of hidden layers

# RNN-specific parameters
RNN_CONFIG:
  hidden_sizes: [64, 64]  # Size of hidden layers in RNN
  dense_features: 64      # Size of final dense layer

# CPC-specific parameters
CPC_CONFIG:
  temperature: 0.1 # try between 0.1 and 0.5
  num_negatives: 32
  num_future_steps: 3
  projection_dim: 128
  gru_hidden_dim: 256
  cpc_coef: 0.1  # Set to 0.0 to ablate CPC loss
  visualize_every: 10000  # Steps between representation visualizations

# Environment Settings
ENV_NAME: "overcooked"                
ENV_KWARGS: 
  layout: "cramped_room"             

ACTIVATION: "relu"                    # tanh or relu, relu for cnn

# PPO Hyperparameters
LR: 2.5e-4                           
ANNEAL_LR: true                       
NUM_ENVS: 64                          
NUM_STEPS: 256                        
TOTAL_TIMESTEPS: 5e7                  # 4e8 for ff, 5e7 for cnn
UPDATE_EPOCHS: 4                     
NUM_MINIBATCHES: 16                   # 4 for ff, 16 for cnn
GAMMA: 0.99                           
GAE_LAMBDA: 0.95                      
CLIP_EPS: 0.2                        
ENT_COEF: 0.01                        
VF_COEF: 0.5                          
MAX_GRAD_NORM: 0.5                    
REW_SHAPING_HORIZON: 2.5e6               # 2.5e7 for ff, 2e4 for cnn

# WandB Integration
ENTITY: "sandily"                     
PROJECT: "comparisons"                
WANDB_MODE: "online"                  