# General Experiment Settings
SEED: 30                              
NUM_SEEDS: 128                         
LOAD_PATH: /nas/ucb/sandytanwisuth/ser/value-of-intent/saved_models/20250228/forced_coord/ub_forced_coord_20250228_170600_30/

# Environment Settings
ENV_NAME: "overcooked"                
ENV_KWARGS: 
  layout: "forced_coord"         

ACTIVATION: "tanh"                    # tanh or relu

# PPO Hyperparameters
LR: 0.0001                          
ANNEAL_LR: true                       
NUM_ENVS: 128                         # 128 for ub, maybe 64 for lb and op or 128 is fins too
NUM_STEPS: 128                        
TOTAL_TIMESTEPS: 4e8                  # 4e8 for all
UPDATE_EPOCHS: 4                      
NUM_MINIBATCHES: 4                    
GAMMA: 0.98                           
GAE_LAMBDA: 0.95                      
CLIP_EPS: 0.2                         
ENT_COEF: 0.05                        
VF_COEF: 0.5                          
MAX_GRAD_NORM: 0.5                    
REW_SHAPING_HORIZON: 2.5e7            

# Transformer Settings
SEQ_LEN: 5

# WandB Integration
ENTITY: "sandily"                     
PROJECT: "comparisons"                
WANDB_MODE: "online"                 